name: "Grav"
description: "Fast, Simple, and Flexible, file-based Web-platform"
url: https://getgrav.org/
version: "1.7.49.5"
slug: grav 
arch:
  - aarch64
  - amd64
init: false
ports:
  16198/tcp: 16198
ports_description:
  16198/tcp: HTTP
#ingress: true

